/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.HorarioDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import Model.Horario;
import DAO.HorarioDAO;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import static javax.swing.JTable.PrintMode.FIT_WIDTH;

/**
 *
 * @author Gustavo Girardon
 */
public class HorarioProfessor extends javax.swing.JFrame {

    /**
     * Creates new form HorarioProfessor
     */
    public HorarioProfessor() {
        initComponents();
        this.setLocationRelativeTo(null);
        popularComboProfessor();
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbProfessor = new javax.swing.JComboBox<>();
        jpHorarioManha = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lblSeg2 = new javax.swing.JLabel();
        lblSeg3 = new javax.swing.JLabel();
        lblSeg4 = new javax.swing.JLabel();
        lblSeg5 = new javax.swing.JLabel();
        lblSeg1 = new javax.swing.JLabel();
        lblTer1 = new javax.swing.JLabel();
        lblTer2 = new javax.swing.JLabel();
        lblTer3 = new javax.swing.JLabel();
        lblTer4 = new javax.swing.JLabel();
        lblQua6 = new javax.swing.JLabel();
        lblSeg6 = new javax.swing.JLabel();
        lblQua1 = new javax.swing.JLabel();
        lblQua2 = new javax.swing.JLabel();
        lblQua3 = new javax.swing.JLabel();
        lblQua4 = new javax.swing.JLabel();
        lblQua5 = new javax.swing.JLabel();
        lblTer5 = new javax.swing.JLabel();
        lblTer6 = new javax.swing.JLabel();
        lblSex1 = new javax.swing.JLabel();
        lblSex2 = new javax.swing.JLabel();
        lblSex3 = new javax.swing.JLabel();
        lblSex4 = new javax.swing.JLabel();
        lblSex5 = new javax.swing.JLabel();
        lblSex6 = new javax.swing.JLabel();
        lblQui1 = new javax.swing.JLabel();
        lblQui2 = new javax.swing.JLabel();
        lblQui3 = new javax.swing.JLabel();
        lblQui4 = new javax.swing.JLabel();
        lblQui5 = new javax.swing.JLabel();
        lblQui6 = new javax.swing.JLabel();
        lblSab1 = new javax.swing.JLabel();
        lblSab2 = new javax.swing.JLabel();
        lblSab3 = new javax.swing.JLabel();
        lblSab4 = new javax.swing.JLabel();
        lblSab5 = new javax.swing.JLabel();
        lblSab6 = new javax.swing.JLabel();
        lblCurso3 = new javax.swing.JLabel();
        lblCurso6 = new javax.swing.JLabel();
        lblCurso2 = new javax.swing.JLabel();
        lblCurso1 = new javax.swing.JLabel();
        lblCurso4 = new javax.swing.JLabel();
        lblCurso5 = new javax.swing.JLabel();
        lblCurso7 = new javax.swing.JLabel();
        lblCurso8 = new javax.swing.JLabel();
        lblCurso9 = new javax.swing.JLabel();
        lblCurso10 = new javax.swing.JLabel();
        lblCurso11 = new javax.swing.JLabel();
        lblCurso12 = new javax.swing.JLabel();
        lblCurso13 = new javax.swing.JLabel();
        lblCurso14 = new javax.swing.JLabel();
        lblCurso15 = new javax.swing.JLabel();
        lblCurso16 = new javax.swing.JLabel();
        lblCurso17 = new javax.swing.JLabel();
        lblCurso18 = new javax.swing.JLabel();
        lblCurso19 = new javax.swing.JLabel();
        lblCurso20 = new javax.swing.JLabel();
        lblCurso21 = new javax.swing.JLabel();
        lblCurso22 = new javax.swing.JLabel();
        lblCurso23 = new javax.swing.JLabel();
        lblCurso24 = new javax.swing.JLabel();
        lblCurso25 = new javax.swing.JLabel();
        lblCurso26 = new javax.swing.JLabel();
        lblCurso27 = new javax.swing.JLabel();
        lblCurso28 = new javax.swing.JLabel();
        lblCurso29 = new javax.swing.JLabel();
        lblCurso30 = new javax.swing.JLabel();
        lblCurso31 = new javax.swing.JLabel();
        lblCurso32 = new javax.swing.JLabel();
        lblCurso33 = new javax.swing.JLabel();
        lblCurso34 = new javax.swing.JLabel();
        lblCurso35 = new javax.swing.JLabel();
        lblCurso36 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        lblPeriodo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblNomeProfessor = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbPeriodo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1026, 668));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel1.setText("Professor");

        cmbProfessor.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        cmbProfessor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProfessorItemStateChanged(evt);
            }
        });
        cmbProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProfessorActionPerformed(evt);
            }
        });

        jpHorarioManha.setBackground(new java.awt.Color(255, 255, 255));
        jpHorarioManha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpHorarioManha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel2.setText("Segunda");
        jpHorarioManha.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 24, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel3.setText("Terça");
        jpHorarioManha.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 24, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel4.setText("Quarta");
        jpHorarioManha.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel5.setText("Quinta");
        jpHorarioManha.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel6.setText("Sexta");
        jpHorarioManha.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel7.setText("Sábado");
        jpHorarioManha.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpHorarioManha.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 24, 15, 430));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpHorarioManha.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 24, 15, 430));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpHorarioManha.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 15, 430));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpHorarioManha.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 15, 430));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpHorarioManha.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 10, 430));

        lblSeg2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeg2.setForeground(new java.awt.Color(204, 0, 0));
        lblSeg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeg2.setText("----------------");
        jpHorarioManha.add(lblSeg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 142, -1));

        lblSeg3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeg3.setForeground(new java.awt.Color(204, 0, 0));
        lblSeg3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeg3.setText("----------------");
        jpHorarioManha.add(lblSeg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 142, -1));

        lblSeg4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeg4.setForeground(new java.awt.Color(204, 0, 0));
        lblSeg4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeg4.setText("----------------");
        jpHorarioManha.add(lblSeg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 142, -1));

        lblSeg5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeg5.setForeground(new java.awt.Color(204, 0, 0));
        lblSeg5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeg5.setText("----------------");
        jpHorarioManha.add(lblSeg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 142, -1));

        lblSeg1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeg1.setForeground(new java.awt.Color(204, 0, 0));
        lblSeg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeg1.setText("----------------");
        jpHorarioManha.add(lblSeg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 72, 142, -1));

        lblTer1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTer1.setForeground(new java.awt.Color(204, 0, 0));
        lblTer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTer1.setText("----------------");
        jpHorarioManha.add(lblTer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 70, 150, -1));

        lblTer2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTer2.setForeground(new java.awt.Color(204, 0, 0));
        lblTer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTer2.setText("----------------");
        jpHorarioManha.add(lblTer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 150, -1));

        lblTer3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTer3.setForeground(new java.awt.Color(204, 0, 0));
        lblTer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTer3.setText("----------------");
        jpHorarioManha.add(lblTer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 150, -1));

        lblTer4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTer4.setForeground(new java.awt.Color(204, 0, 0));
        lblTer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTer4.setText("----------------");
        jpHorarioManha.add(lblTer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, -1));

        lblQua6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQua6.setForeground(new java.awt.Color(204, 0, 0));
        lblQua6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQua6.setText("----------------");
        jpHorarioManha.add(lblQua6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 150, -1));

        lblSeg6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeg6.setForeground(new java.awt.Color(204, 0, 0));
        lblSeg6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeg6.setText("----------------");
        jpHorarioManha.add(lblSeg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 142, -1));

        lblQua1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQua1.setForeground(new java.awt.Color(204, 0, 0));
        lblQua1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQua1.setText("----------------");
        jpHorarioManha.add(lblQua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 150, -1));

        lblQua2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQua2.setForeground(new java.awt.Color(204, 0, 0));
        lblQua2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQua2.setText("----------------");
        jpHorarioManha.add(lblQua2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 150, -1));

        lblQua3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQua3.setForeground(new java.awt.Color(204, 0, 0));
        lblQua3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQua3.setText("----------------");
        jpHorarioManha.add(lblQua3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 150, -1));

        lblQua4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQua4.setForeground(new java.awt.Color(204, 0, 0));
        lblQua4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQua4.setText("----------------");
        jpHorarioManha.add(lblQua4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 150, -1));

        lblQua5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQua5.setForeground(new java.awt.Color(204, 0, 0));
        lblQua5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQua5.setText("----------------");
        jpHorarioManha.add(lblQua5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 150, -1));

        lblTer5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTer5.setForeground(new java.awt.Color(204, 0, 0));
        lblTer5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTer5.setText("----------------");
        jpHorarioManha.add(lblTer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 150, -1));

        lblTer6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTer6.setForeground(new java.awt.Color(204, 0, 0));
        lblTer6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTer6.setText("----------------");
        jpHorarioManha.add(lblTer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 150, -1));

        lblSex1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSex1.setForeground(new java.awt.Color(204, 0, 0));
        lblSex1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSex1.setText("----------------");
        jpHorarioManha.add(lblSex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 150, -1));

        lblSex2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSex2.setForeground(new java.awt.Color(204, 0, 0));
        lblSex2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSex2.setText("----------------");
        jpHorarioManha.add(lblSex2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 150, -1));

        lblSex3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSex3.setForeground(new java.awt.Color(204, 0, 0));
        lblSex3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSex3.setText("----------------");
        jpHorarioManha.add(lblSex3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 150, -1));

        lblSex4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSex4.setForeground(new java.awt.Color(204, 0, 0));
        lblSex4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSex4.setText("----------------");
        jpHorarioManha.add(lblSex4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 150, -1));

        lblSex5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSex5.setForeground(new java.awt.Color(204, 0, 0));
        lblSex5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSex5.setText("----------------");
        jpHorarioManha.add(lblSex5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 150, -1));

        lblSex6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSex6.setForeground(new java.awt.Color(204, 0, 0));
        lblSex6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSex6.setText("----------------");
        jpHorarioManha.add(lblSex6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 150, -1));

        lblQui1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQui1.setForeground(new java.awt.Color(204, 0, 0));
        lblQui1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQui1.setText("----------------");
        jpHorarioManha.add(lblQui1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 150, -1));

        lblQui2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQui2.setForeground(new java.awt.Color(204, 0, 0));
        lblQui2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQui2.setText("----------------");
        jpHorarioManha.add(lblQui2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 150, -1));

        lblQui3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQui3.setForeground(new java.awt.Color(204, 0, 0));
        lblQui3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQui3.setText("----------------");
        jpHorarioManha.add(lblQui3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 150, -1));

        lblQui4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQui4.setForeground(new java.awt.Color(204, 0, 0));
        lblQui4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQui4.setText("----------------");
        jpHorarioManha.add(lblQui4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 150, -1));

        lblQui5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQui5.setForeground(new java.awt.Color(204, 0, 0));
        lblQui5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQui5.setText("----------------");
        jpHorarioManha.add(lblQui5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 150, -1));

        lblQui6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQui6.setForeground(new java.awt.Color(204, 0, 0));
        lblQui6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQui6.setText("----------------");
        jpHorarioManha.add(lblQui6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 150, -1));

        lblSab1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSab1.setForeground(new java.awt.Color(204, 0, 0));
        lblSab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSab1.setText("----------------");
        jpHorarioManha.add(lblSab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 150, -1));

        lblSab2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSab2.setForeground(new java.awt.Color(204, 0, 0));
        lblSab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSab2.setText("----------------");
        jpHorarioManha.add(lblSab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 150, -1));

        lblSab3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSab3.setForeground(new java.awt.Color(204, 0, 0));
        lblSab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSab3.setText("----------------");
        jpHorarioManha.add(lblSab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 150, -1));

        lblSab4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSab4.setForeground(new java.awt.Color(204, 0, 0));
        lblSab4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSab4.setText("----------------");
        jpHorarioManha.add(lblSab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 150, -1));

        lblSab5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSab5.setForeground(new java.awt.Color(204, 0, 0));
        lblSab5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSab5.setText("----------------");
        jpHorarioManha.add(lblSab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 150, -1));

        lblSab6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSab6.setForeground(new java.awt.Color(204, 0, 0));
        lblSab6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSab6.setText("----------------");
        jpHorarioManha.add(lblSab6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 150, -1));

        lblCurso3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso3.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso3.setText("----------");
        lblCurso3.setToolTipText("");
        jpHorarioManha.add(lblCurso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, -1));

        lblCurso6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso6.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso6.setText("----------");
        lblCurso6.setToolTipText("");
        jpHorarioManha.add(lblCurso6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 100, -1));

        lblCurso2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso2.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso2.setText("----------");
        lblCurso2.setToolTipText("");
        jpHorarioManha.add(lblCurso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, -1));

        lblCurso1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso1.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso1.setText("----------");
        lblCurso1.setToolTipText("");
        jpHorarioManha.add(lblCurso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, -1));

        lblCurso4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso4.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso4.setText("----------");
        lblCurso4.setToolTipText("");
        jpHorarioManha.add(lblCurso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, -1));

        lblCurso5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso5.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso5.setText("----------");
        lblCurso5.setToolTipText("");
        jpHorarioManha.add(lblCurso5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, -1));

        lblCurso7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso7.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso7.setText("----------");
        lblCurso7.setToolTipText("");
        jpHorarioManha.add(lblCurso7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, -1));

        lblCurso8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso8.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso8.setText("----------");
        lblCurso8.setToolTipText("");
        jpHorarioManha.add(lblCurso8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));

        lblCurso9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso9.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso9.setText("----------");
        lblCurso9.setToolTipText("");
        jpHorarioManha.add(lblCurso9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 150, -1));

        lblCurso10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso10.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso10.setText("----------");
        lblCurso10.setToolTipText("");
        jpHorarioManha.add(lblCurso10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 150, -1));

        lblCurso11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso11.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso11.setText("----------");
        lblCurso11.setToolTipText("");
        jpHorarioManha.add(lblCurso11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 150, -1));

        lblCurso12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso12.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso12.setText("----------");
        lblCurso12.setToolTipText("");
        jpHorarioManha.add(lblCurso12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 150, -1));

        lblCurso13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso13.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso13.setText("----------");
        lblCurso13.setToolTipText("");
        jpHorarioManha.add(lblCurso13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 150, -1));

        lblCurso14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso14.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso14.setText("----------");
        lblCurso14.setToolTipText("");
        jpHorarioManha.add(lblCurso14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 150, -1));

        lblCurso15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso15.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso15.setText("----------");
        lblCurso15.setToolTipText("");
        jpHorarioManha.add(lblCurso15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 150, -1));

        lblCurso16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso16.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso16.setText("----------");
        lblCurso16.setToolTipText("");
        jpHorarioManha.add(lblCurso16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 160, -1));

        lblCurso17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso17.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso17.setText("----------");
        lblCurso17.setToolTipText("");
        jpHorarioManha.add(lblCurso17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 150, -1));

        lblCurso18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso18.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso18.setText("----------");
        lblCurso18.setToolTipText("");
        jpHorarioManha.add(lblCurso18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 150, -1));

        lblCurso19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso19.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso19.setText("----------");
        lblCurso19.setToolTipText("");
        jpHorarioManha.add(lblCurso19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 150, -1));

        lblCurso20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso20.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso20.setText("----------");
        lblCurso20.setToolTipText("");
        jpHorarioManha.add(lblCurso20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 150, -1));

        lblCurso21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso21.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso21.setText("----------");
        lblCurso21.setToolTipText("");
        jpHorarioManha.add(lblCurso21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 150, -1));

        lblCurso22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso22.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso22.setText("----------");
        lblCurso22.setToolTipText("");
        jpHorarioManha.add(lblCurso22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 150, -1));

        lblCurso23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso23.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso23.setText("----------");
        lblCurso23.setToolTipText("");
        jpHorarioManha.add(lblCurso23, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 150, -1));

        lblCurso24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso24.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso24.setText("----------");
        lblCurso24.setToolTipText("");
        jpHorarioManha.add(lblCurso24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 150, -1));

        lblCurso25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso25.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso25.setText("----------");
        lblCurso25.setToolTipText("");
        jpHorarioManha.add(lblCurso25, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 150, -1));

        lblCurso26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso26.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso26.setText("----------");
        lblCurso26.setToolTipText("");
        jpHorarioManha.add(lblCurso26, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 150, -1));

        lblCurso27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso27.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso27.setText("----------");
        lblCurso27.setToolTipText("");
        jpHorarioManha.add(lblCurso27, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 150, -1));

        lblCurso28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso28.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso28.setText("----------");
        lblCurso28.setToolTipText("");
        jpHorarioManha.add(lblCurso28, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 150, -1));

        lblCurso29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso29.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso29.setText("----------");
        lblCurso29.setToolTipText("");
        jpHorarioManha.add(lblCurso29, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 150, -1));

        lblCurso30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso30.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso30.setText("----------");
        lblCurso30.setToolTipText("");
        jpHorarioManha.add(lblCurso30, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 150, -1));

        lblCurso31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso31.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso31.setText("----------");
        lblCurso31.setToolTipText("");
        jpHorarioManha.add(lblCurso31, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 150, -1));

        lblCurso32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso32.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso32.setText("----------");
        lblCurso32.setToolTipText("");
        jpHorarioManha.add(lblCurso32, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 150, -1));

        lblCurso33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso33.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso33.setText("----------");
        lblCurso33.setToolTipText("");
        jpHorarioManha.add(lblCurso33, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 150, -1));

        lblCurso34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso34.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso34.setText("----------");
        lblCurso34.setToolTipText("");
        jpHorarioManha.add(lblCurso34, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 150, -1));

        lblCurso35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso35.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso35.setText("----------");
        lblCurso35.setToolTipText("");
        jpHorarioManha.add(lblCurso35, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 150, -1));

        lblCurso36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurso36.setForeground(new java.awt.Color(0, 51, 255));
        lblCurso36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso36.setText("----------");
        lblCurso36.setToolTipText("");
        jpHorarioManha.add(lblCurso36, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 150, -1));

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblPeriodo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lblPeriodo.setForeground(new java.awt.Color(255, 0, 0));
        lblPeriodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPeriodo.setText("Manhã");
        lblPeriodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPeriodoMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel9.setText("1º Aula");

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel10.setText("2º Aula");

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel11.setText("3º Aula");

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel12.setText("4º Aula");

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel13.setText("5º Aula");

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel14.setText("6º Aula");

        lblNomeProfessor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNomeProfessor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeProfessor.setText("Nome");

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel8.setText("Período");

        cmbPeriodo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));
        cmbPeriodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPeriodoItemStateChanged(evt);
            }
        });
        cmbPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPeriodoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(lblNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cmbProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpHorarioManha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(452, 452, 452))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblPeriodo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel9)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel10)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel11)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel12)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel13)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jpHorarioManha, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProfessorActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String professor = cmbProfessor.getSelectedItem().toString();
        String periodo = cmbPeriodo.getSelectedItem().toString();
        if(periodo == null){
            periodo = "Manhã";
        } else {
        limparLabels();
        Semana(professor, periodo);
        lblNomeProfessor.setText(professor);
        lblPeriodo.setText(periodo);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void cmbProfessorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProfessorItemStateChanged
        String professor = cmbProfessor.getSelectedItem().toString();
        String periodo = cmbPeriodo.getSelectedItem().toString();
        if(periodo == null){
            periodo = "Manhã";
        } else {
        limparLabels();
        Semana(professor, periodo);
        lblNomeProfessor.setText(professor);
        lblPeriodo.setText(periodo);
        }
    }//GEN-LAST:event_cmbProfessorItemStateChanged

    private void lblPeriodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPeriodoMouseClicked
        
        
    }//GEN-LAST:event_lblPeriodoMouseClicked

    private void cmbPeriodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPeriodoItemStateChanged
        String professor = cmbProfessor.getSelectedItem().toString();
        String periodo = cmbPeriodo.getSelectedItem().toString();
        if(periodo == null){
            periodo = "Manhã";
        } else {
        limparLabels();
        Semana(professor, periodo);
        lblNomeProfessor.setText(professor);
        lblPeriodo.setText(periodo);
        }
    }//GEN-LAST:event_cmbPeriodoItemStateChanged

    private void cmbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPeriodoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //printComponenet();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HorarioProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HorarioProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HorarioProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HorarioProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HorarioProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cmbPeriodo;
    private javax.swing.JComboBox<String> cmbProfessor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel jpHorarioManha;
    private javax.swing.JLabel lblCurso1;
    private javax.swing.JLabel lblCurso10;
    private javax.swing.JLabel lblCurso11;
    private javax.swing.JLabel lblCurso12;
    private javax.swing.JLabel lblCurso13;
    private javax.swing.JLabel lblCurso14;
    private javax.swing.JLabel lblCurso15;
    private javax.swing.JLabel lblCurso16;
    private javax.swing.JLabel lblCurso17;
    private javax.swing.JLabel lblCurso18;
    private javax.swing.JLabel lblCurso19;
    private javax.swing.JLabel lblCurso2;
    private javax.swing.JLabel lblCurso20;
    private javax.swing.JLabel lblCurso21;
    private javax.swing.JLabel lblCurso22;
    private javax.swing.JLabel lblCurso23;
    private javax.swing.JLabel lblCurso24;
    private javax.swing.JLabel lblCurso25;
    private javax.swing.JLabel lblCurso26;
    private javax.swing.JLabel lblCurso27;
    private javax.swing.JLabel lblCurso28;
    private javax.swing.JLabel lblCurso29;
    private javax.swing.JLabel lblCurso3;
    private javax.swing.JLabel lblCurso30;
    private javax.swing.JLabel lblCurso31;
    private javax.swing.JLabel lblCurso32;
    private javax.swing.JLabel lblCurso33;
    private javax.swing.JLabel lblCurso34;
    private javax.swing.JLabel lblCurso35;
    private javax.swing.JLabel lblCurso36;
    private javax.swing.JLabel lblCurso4;
    private javax.swing.JLabel lblCurso5;
    private javax.swing.JLabel lblCurso6;
    private javax.swing.JLabel lblCurso7;
    private javax.swing.JLabel lblCurso8;
    private javax.swing.JLabel lblCurso9;
    private javax.swing.JLabel lblNomeProfessor;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblQua1;
    private javax.swing.JLabel lblQua2;
    private javax.swing.JLabel lblQua3;
    private javax.swing.JLabel lblQua4;
    private javax.swing.JLabel lblQua5;
    private javax.swing.JLabel lblQua6;
    private javax.swing.JLabel lblQui1;
    private javax.swing.JLabel lblQui2;
    private javax.swing.JLabel lblQui3;
    private javax.swing.JLabel lblQui4;
    private javax.swing.JLabel lblQui5;
    private javax.swing.JLabel lblQui6;
    private javax.swing.JLabel lblSab1;
    private javax.swing.JLabel lblSab2;
    private javax.swing.JLabel lblSab3;
    private javax.swing.JLabel lblSab4;
    private javax.swing.JLabel lblSab5;
    private javax.swing.JLabel lblSab6;
    private javax.swing.JLabel lblSeg1;
    private javax.swing.JLabel lblSeg2;
    private javax.swing.JLabel lblSeg3;
    private javax.swing.JLabel lblSeg4;
    private javax.swing.JLabel lblSeg5;
    private javax.swing.JLabel lblSeg6;
    private javax.swing.JLabel lblSex1;
    private javax.swing.JLabel lblSex2;
    private javax.swing.JLabel lblSex3;
    private javax.swing.JLabel lblSex4;
    private javax.swing.JLabel lblSex5;
    private javax.swing.JLabel lblSex6;
    private javax.swing.JLabel lblTer1;
    private javax.swing.JLabel lblTer2;
    private javax.swing.JLabel lblTer3;
    private javax.swing.JLabel lblTer4;
    private javax.swing.JLabel lblTer5;
    private javax.swing.JLabel lblTer6;
    // End of variables declaration//GEN-END:variables
    
    
    public final void popularComboProfessor(){
        HorarioDAO a = new HorarioDAO();
        Connection conn = null;
         
         try {
            conn = a.abrirConexao();
            //BUSCA DE TODOS OS NOMES CONTIDOS NA TABELA
            if(conn != null){
                String Consulta = "SELECT nome FROM Professor ORDER BY nome";
                Statement stm = conn.createStatement();
                ResultSet resultado = stm.executeQuery(Consulta);
                
                int cont = 0;
                List<String> list = new ArrayList<String>();
                //LOOP REALIZADO PARA PREENCHER A LIST COM OS VALORES RETORNADOS
                while( resultado.next() ) {    
                cont++;
           
                String nome = resultado.getString("Nome"); 
                
                list.add(nome);
                DefaultComboBoxModel defaultComboModel = new DefaultComboBoxModel(list.toArray());
                cmbProfessor.setModel(defaultComboModel);
              
                }
                
            }
        } catch(SQLException ex){
            System.out.println("Erro ao consultar os dados do BD.");
        } finally {
            a.fecharConexao(conn);
        }
        
    }
    
    public final void AulaSegunda(String professor, String periodo){
        HorarioDAO p = new HorarioDAO();
        Connection conn = null;
        String[] coluna = null;
         try {
            conn = p.abrirConexao();
           
            if(conn != null){
                String Consulta = "SELECT  Aula, NomeDisciplina FROM Horario WHERE NomeProfessor = '"+professor+"' AND DiaSemana='Segunda' AND  Periodo = '"+periodo+"'";
                Statement stm = conn.createStatement();
                ResultSet resultado = stm.executeQuery(Consulta);
                
                int cont = 0;           
                while( resultado.next() ) {    
                cont++;
                
                String aula = resultado.getString("Aula"); 
                String disciplina = resultado.getString("NomeDisciplina"); 
                
                switch(aula){
                    case "1º Aula":
                        lblSeg1.setText(disciplina);
                        lblCurso1.setText(buscarCurso(lblSeg1.getText()));
                        break;
                    case "2º Aula":
                        lblSeg2.setText(disciplina);
                        lblCurso2.setText(buscarCurso(lblSeg2.getText()));
                        break;
                    case "3º Aula":
                        lblSeg3.setText(disciplina);
                        buscarCurso(lblSeg3.getText());
                        lblCurso3.setText(buscarCurso(lblSeg3.getText()));
                        break;
                    case "4º Aula":
                        lblSeg4.setText(disciplina);
                        buscarCurso(lblSeg4.getText());
                        lblCurso4.setText(buscarCurso(lblSeg4.getText()));
                        break;
                    case "5º Aula":
                        lblSeg5.setText(disciplina);
                        buscarCurso(lblSeg5.getText());
                        lblCurso5.setText(buscarCurso(lblSeg5.getText()));
                        break;
                    case "6º Aula":
                        lblSeg6.setText(disciplina);
                        buscarCurso(lblSeg6.getText());
                        lblCurso6.setText(buscarCurso(lblSeg6.getText()));
                        break;
                    default:
                        break;
                    
                }
                
                
                }
            }
        } catch(SQLException ex){
            System.out.println("Erro ao consultar os dados do BD.");
        } finally {
            p.fecharConexao(conn);
        }
        
    }
    
    public final void AulaTerca(String professor, String periodo){
        HorarioDAO p = new HorarioDAO();
        Connection conn = null;
        String[] coluna = null;
         try {
            conn = p.abrirConexao();
           
            if(conn != null){
                String Consulta = "SELECT  Aula, NomeDisciplina FROM Horario WHERE NomeProfessor = '"+professor+"' AND DiaSemana='Terça' AND Periodo = '"+periodo+"'";
                Statement stm = conn.createStatement();
                ResultSet resultado = stm.executeQuery(Consulta);
                
                int cont = 0;           
                while( resultado.next() ) {    
                cont++;
                
                String aula = resultado.getString("Aula"); 
                String disciplina = resultado.getString("NomeDisciplina"); 
                
                switch(aula){
                    case "1º Aula":
                        lblTer1.setText(disciplina);
                        lblCurso7.setText(buscarCurso(lblTer1.getText()));
                        break;
                    case "2º Aula":
                        lblTer2.setText(disciplina);
                        lblCurso8.setText(buscarCurso(lblTer2.getText()));
                        break;
                    case "3º Aula":
                        lblTer3.setText(disciplina);
                        lblCurso9.setText(buscarCurso(lblTer3.getText()));
                        break;
                    case "4º Aula":
                        lblTer4.setText(disciplina);
                        lblCurso10.setText(buscarCurso(lblTer4.getText()));
                        break;
                    case "5º Aula":
                        lblTer5.setText(disciplina);
                        lblCurso11.setText(buscarCurso(lblTer5.getText()));
                        break;
                    case "6º Aula":
                        lblTer6.setText(disciplina);
                        lblCurso12.setText(buscarCurso(lblTer6.getText()));
                        break;
                    default:
                        break;
                    
                }
                
                }
            }
        } catch(SQLException ex){
            System.out.println("Erro ao consultar os dados do BD.");
        } finally {
            p.fecharConexao(conn);
        }
    }
    
    public final void AulaQuarta(String professor, String periodo){
        HorarioDAO p = new HorarioDAO();
        Connection conn = null;
        String[] coluna = null;
         try {
            conn = p.abrirConexao();
           
            if(conn != null){
                String Consulta = "SELECT  Aula, NomeDisciplina FROM Horario WHERE NomeProfessor = '"+professor+"' AND DiaSemana='Quarta' AND Periodo = '"+periodo+"'";
                Statement stm = conn.createStatement();
                ResultSet resultado = stm.executeQuery(Consulta);
                
                int cont = 0;           
                while( resultado.next() ) {    
                cont++;
                
                String aula = resultado.getString("Aula"); 
                String disciplina = resultado.getString("NomeDisciplina"); 
                
                switch(aula){
                    case "1º Aula":
                        lblQua1.setText(disciplina);
                        lblCurso13.setText(buscarCurso(lblQua1.getText()));
                        break;
                    case "2º Aula":
                        lblQua2.setText(disciplina);
                        lblCurso14.setText(buscarCurso(lblQua2.getText()));
                        break;
                    case "3º Aula":
                        lblQua3.setText(disciplina);
                        lblCurso15.setText(buscarCurso(lblQua3.getText()));
                        break;
                    case "4º Aula":
                        lblQua4.setText(disciplina);
                        lblCurso16.setText(buscarCurso(lblQua4.getText()));
                        break;
                    case "5º Aula":
                        lblQua5.setText(disciplina);
                        lblCurso17.setText(buscarCurso(lblQua5.getText()));
                        break;
                    case "6º Aula":
                        lblQua6.setText(disciplina);
                        lblCurso18.setText(buscarCurso(lblQua6.getText()));
                        break;
                    default:
                        break;
                    
                }
                
                }
            }
        } catch(SQLException ex){
            System.out.println("Erro ao consultar os dados do BD.");
        } finally {
            p.fecharConexao(conn);
        }
    }
    
    public final void AulaQuinta(String professor, String periodo){
        HorarioDAO p = new HorarioDAO();
        Connection conn = null;
        String[] coluna = null;
         try {
            conn = p.abrirConexao();
           
            if(conn != null){
                String Consulta = "SELECT  Aula, NomeDisciplina FROM Horario WHERE NomeProfessor = '"+professor+"' AND DiaSemana='Quinta' AND Periodo = '"+periodo+"'";
                Statement stm = conn.createStatement();
                ResultSet resultado = stm.executeQuery(Consulta);
                
                int cont = 0;           
                while( resultado.next() ) {    
                cont++;
                
                String aula = resultado.getString("Aula"); 
                String disciplina = resultado.getString("NomeDisciplina"); 
                
                switch(aula){
                    case "1º Aula":
                        lblQui1.setText(disciplina);
                        lblCurso19.setText(buscarCurso(lblQui1.getText()));
                        break;
                    case "2º Aula":
                        lblQui2.setText(disciplina);
                        lblCurso20.setText(buscarCurso(lblQui2.getText()));
                        break;
                    case "3º Aula":
                        lblQui3.setText(disciplina);
                        lblCurso21.setText(buscarCurso(lblQui3.getText()));
                        break;
                    case "4º Aula":
                        lblQui4.setText(disciplina);
                        lblCurso22.setText(buscarCurso(lblQui4.getText()));
                        break;
                    case "5º Aula":
                        lblQui5.setText(disciplina);
                        lblCurso23.setText(buscarCurso(lblQui5.getText()));
                        break;
                    case "6º Aula":
                        lblQui6.setText(disciplina);
                        lblCurso24.setText(buscarCurso(lblQui6.getText()));
                        break;
                    default:
                        break;
                    
                }
                
                }
            }
        } catch(SQLException ex){
            System.out.println("Erro ao consultar os dados do BD.");
        } finally {
            p.fecharConexao(conn);
        }
    }
    
    public final void AulaSexta(String professor, String periodo){
        HorarioDAO p = new HorarioDAO();
        Connection conn = null;
        String[] coluna = null;
         try {
            conn = p.abrirConexao();
           
            if(conn != null){
                String Consulta = "SELECT  Aula, NomeDisciplina FROM Horario WHERE NomeProfessor = '"+professor+"' AND DiaSemana='Sexta' AND Periodo = '"+periodo+"'";
                Statement stm = conn.createStatement();
                ResultSet resultado = stm.executeQuery(Consulta);
                
                int cont = 0;           
                while( resultado.next() ) {    
                cont++;
                
                String aula = resultado.getString("Aula"); 
                String disciplina = resultado.getString("NomeDisciplina"); 
                
                switch(aula){
                    case "1º Aula":
                        lblSex1.setText(disciplina);
                        lblCurso25.setText(buscarCurso(lblSex1.getText()));
                        break;
                    case "2º Aula":
                        lblSex2.setText(disciplina);
                        lblCurso26.setText(buscarCurso(lblSex2.getText()));
                        break;
                    case "3º Aula":
                        lblSex3.setText(disciplina);
                        lblCurso27.setText(buscarCurso(lblSex3.getText()));
                        break;
                    case "4º Aula":
                        lblSex4.setText(disciplina);
                        lblCurso28.setText(buscarCurso(lblSex4.getText()));
                        break;
                    case "5º Aula":
                        lblSex5.setText(disciplina);
                        lblCurso29.setText(buscarCurso(lblSex5.getText()));
                        break;
                    case "6º Aula":
                        lblSex6.setText(disciplina);
                        lblCurso30.setText(buscarCurso(lblSex6.getText()));
                        break;
                    default:
                        break;
                    
                }
                
                }
            }
        } catch(SQLException ex){
            System.out.println("Erro ao consultar os dados do BD.");
        } finally {
            p.fecharConexao(conn);
        }
    }
    
    public final void AulaSabado(String professor, String periodo){
        HorarioDAO p = new HorarioDAO();
        Connection conn = null;
        String[] coluna = null;
         try {
            conn = p.abrirConexao();
           
            if(conn != null){
                String Consulta = "SELECT  Aula, NomeDisciplina FROM Horario WHERE NomeProfessor = '"+professor+"' AND DiaSemana='Sábado' AND Periodo = '"+periodo+"'";
                Statement stm = conn.createStatement();
                ResultSet resultado = stm.executeQuery(Consulta);
                
                int cont = 0;           
                while( resultado.next() ) {    
                cont++;
                
                String aula = resultado.getString("Aula"); 
                String disciplina = resultado.getString("NomeDisciplina"); 
                
                switch(aula){
                    case "1º Aula":
                        lblSab1.setText(disciplina);
                        lblCurso31.setText(buscarCurso(lblSab1.getText()));
                        break;
                    case "2º Aula":
                        lblSab2.setText(disciplina);
                        lblCurso32.setText(buscarCurso(lblSab2.getText()));
                        break;
                    case "3º Aula":
                        lblSab3.setText(disciplina);
                        lblCurso33.setText(buscarCurso(lblSab3.getText()));
                        break;
                    case "4º Aula":
                        lblSab4.setText(disciplina);
                        lblCurso34.setText(buscarCurso(lblSab4.getText()));
                        break;
                    case "5º Aula":
                        lblSab5.setText(disciplina);
                        lblCurso35.setText(buscarCurso(lblSab5.getText()));
                        break;
                    case "6º Aula":
                        lblSab6.setText(disciplina);
                        lblCurso36.setText(buscarCurso(lblSab6.getText()));
                        break;
                    default:
                        break;
                    
                }
                
                }
            }
        } catch(SQLException ex){
            System.out.println("Erro ao consultar os dados do BD.");
        } finally {
            p.fecharConexao(conn);
        }
    }
    
    public void limparLabels(){
        /*SEGUNDA*/
        lblSeg1.setText("----------------");
        lblSeg2.setText("----------------");
        lblSeg3.setText("----------------");
        lblSeg4.setText("----------------");
        lblSeg5.setText("----------------");
        lblSeg6.setText("----------------");
        
        lblCurso1.setText("----------");
        lblCurso2.setText("----------");
        lblCurso3.setText("----------");
        lblCurso4.setText("----------");
        lblCurso5.setText("----------");
        lblCurso6.setText("----------");
        
        /*TERÇA*/
        lblTer1.setText("----------------");
        lblTer2.setText("----------------");
        lblTer3.setText("----------------");
        lblTer4.setText("----------------");
        lblTer5.setText("----------------");
        lblTer6.setText("----------------");
        
        lblCurso7.setText("----------");
        lblCurso8.setText("----------");
        lblCurso9.setText("----------");
        lblCurso10.setText("----------");
        lblCurso11.setText("----------");
        lblCurso12.setText("----------");
        
        /*QUARTA*/
        lblQua1.setText("----------------");
        lblQua2.setText("----------------");
        lblQua3.setText("----------------");
        lblQua4.setText("----------------");
        lblQua5.setText("----------------");
        lblQua6.setText("----------------");
        
        lblCurso13.setText("----------");
        lblCurso14.setText("----------");
        lblCurso15.setText("----------");
        lblCurso16.setText("----------");
        lblCurso17.setText("----------");
        lblCurso18.setText("----------");
        
        /*QUINTA*/
        lblQui1.setText("----------------");
        lblQui2.setText("----------------");
        lblQui3.setText("----------------");
        lblQui4.setText("----------------");
        lblQui5.setText("----------------");
        lblQui6.setText("----------------");
        
        lblCurso19.setText("----------");
        lblCurso20.setText("----------");
        lblCurso21.setText("----------");
        lblCurso22.setText("----------");
        lblCurso23.setText("----------");
        lblCurso24.setText("----------");
        
        /*SEXTA*/
        lblSex1.setText("----------------");
        lblSex2.setText("----------------");
        lblSex3.setText("----------------");
        lblSex4.setText("----------------");
        lblSex5.setText("----------------");
        lblSex6.setText("----------------");
        
        lblCurso25.setText("----------");
        lblCurso26.setText("----------");
        lblCurso27.setText("----------");
        lblCurso28.setText("----------");
        lblCurso29.setText("----------");
        lblCurso30.setText("----------");
        
        /*SÁBADO*/
        lblSab1.setText("----------------");
        lblSab2.setText("----------------");
        lblSab3.setText("----------------");
        lblSab4.setText("----------------");
        lblSab5.setText("----------------");
        lblSab6.setText("----------------");
        
        lblCurso31.setText("----------");
        lblCurso32.setText("----------");
        lblCurso33.setText("----------");
        lblCurso34.setText("----------");
        lblCurso35.setText("----------");
        lblCurso36.setText("----------");
        
        
    }
    
    public void Semana(String professor, String periodo){
        String p = professor;
        String pr = periodo;
        AulaSegunda(p, pr);
        AulaTerca(p, pr);
        AulaQuarta(p, pr);
        AulaQuinta(p, pr);
        AulaSexta(p, pr);
        AulaSabado(p, pr);
    }
    
    public void printComponenet(){
    PrinterJob pj = PrinterJob.getPrinterJob();
    pj.setJobName(" Print Component ");
    pj.setPrintable (new Printable() {    
        public int print(Graphics pg, PageFormat pf, int pageNum){
            if (pageNum > 0){
                return Printable.NO_SUCH_PAGE;
            }
            Graphics2D g2 = (Graphics2D) pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            
            jpHorarioManha.paint(g2);        // o JPanel aqui
            
            return Printable.PAGE_EXISTS;
        }

    });
    if (pj.printDialog() == false)
        return;
    try {
        pj.print();
    } catch (PrinterException ex) {
        // handle exception
    }
}

    public String buscarCurso(String disciplina){
        String curso = "----------";
        
        HorarioDAO a = new HorarioDAO();
        Connection conn = null;
         
         try {
            conn = a.abrirConexao();
            if(conn != null){
                String Consulta = "SELECT nomeCurso FROM Disciplina WHERE nome = '"+disciplina+"'";
                Statement stm = conn.createStatement();
                ResultSet resultado = stm.executeQuery(Consulta);
                
                int cont = 0;
                while( resultado.next() ) {    
                cont++;
           
                curso = resultado.getString("nomeCurso"); 
                }
                
                
            }
        } catch(SQLException ex){
            System.out.println("Erro ao consultar os dados do BD.");
        } finally {
            a.fecharConexao(conn);
        }
        return curso;
    }

}
